name: PR Tutorial Tests

on:
  pull_request:
    paths:
      - 'tutorials/**'
      - '!tutorials/**/scripts/**'
  workflow_dispatch:
    inputs:
      tutorial_slug:
        description: 'Tutorial slug to test (e.g., zero-to-hero)'
        required: true
        type: string

jobs:
  find-changed-tutorials:
    runs-on: ubuntu-latest
    outputs:
      tutorials: ${{ steps.changed.outputs.tutorials }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changed
        env:
          GH_EVENT: ${{ github.event_name }}
          TUTORIAL_SLUG: ${{ inputs.tutorial_slug }}
        run: |
          set -e
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          HEAD_SHA=${{ github.sha }}
          echo "Base: $BASE_SHA"
          echo "Head: $HEAD_SHA"

          # Manual trigger: honor provided tutorial_slug
          if [ "$GH_EVENT" = "workflow_dispatch" ] && [ -n "$TUTORIAL_SLUG" ]; then
            ARR=$(printf '%s\n' "$TUTORIAL_SLUG" | jq -R . | jq -s -c .)
            echo "tutorials=$ARR" >> $GITHUB_OUTPUT
            echo "Manual run for tutorial: $ARR"
            exit 0
          fi
          # List added tutorial slugs
          ADDED=$(git diff --name-status "$BASE_SHA" "$HEAD_SHA" | awk '/^A\t/ {print $2}' | grep '^tutorials/' | cut -d'/' -f2 | sort -u || true)
          if [ -n "$ADDED" ]; then
            ARR=$(printf '%s\n' $ADDED | jq -R . | jq -s -c .)
            echo "tutorials=$ARR" >> $GITHUB_OUTPUT
            echo "Added tutorials: $ARR"
            exit 0
          fi
          # No newly added tutorials: skip tests
          echo 'tutorials=[]' >> $GITHUB_OUTPUT
          echo "No newly added tutorials detected; skipping tests."

  test:
    needs: find-changed-tutorials
    if: needs.find-changed-tutorials.outputs.tutorials != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        slug: ${{ fromJson(needs.find-changed-tutorials.outputs.tutorials) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: tutorials/${{ matrix.slug }}
        run: npm ci || npm i
      - name: Run tests
        working-directory: tutorials/${{ matrix.slug }}
        run: npm run test --silent


